### ISSUE TITLE
Bobtimus

### ISSUE THREAD

**Issue by bonomat** [comit-network/droplet#17]
Bobtimus is in the role of Bob

- rate feed: publish fixed rate every X seconds
- api to implement protocol steps
	- interaction with elementsd
	- user provides an elementsd node with an existing wallet
	- we expect the wallet to remain unlocked forever

**Comment by thomaseizinger** [comment]
Consider the following struct layout:

- `lib.rs`: contains api definition for protocols steps and rate
- `fixed_rate.rs`: module that defines a stream of fixed rates (only declared using `mod` within `bin/fake_bobtimus.rs`)
- `kraken_rate.rs`: module that defines a stream of rates from kraken (only declared using `mod` within `bin/bobtimus.rs`)
- `bin/fake_bobtimus.rs`: uses shared lib code + `fixed_rate.rs` to build a binary
- `bin/bobtimus.rs`: uses shared lib code + `kraken_rate.rs` to build a binary
