### ISSUE TITLE
Frontend Wallet

### ISSUE THREAD

**Issue by bonomat** [comit-network/droplet#18]
only manage certain assets (i.e. bitcoin, usdt)

- create new wallet which takes some kind of randomness 
	- save seed in localstorage
- get new address from wallet to fund
- get balance for multiple assets
- protocol steps 
	- create_new_swap: to initiate a new swap
    - finalize_swap: to finalize a swap
		- publish_transaction
- utxo management against [esplora](https://github.com/Blockstream/esplora)
	- fetch utxos for address
	- store utxos in localstorage
- (optional) encrypt local storage

**Comment by thomaseizinger** [comment]
Mostly done, new issues cover the rest.
