### ISSUE TITLE
Infrastructure: Development environment with local esplora and elementd

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/droplet#34]
Esplora URL for the wallet can be set using `ESPLORA_URL` env variable at **build** time: https://github.com/comit-network/droplet/blob/96687ef6f0c9acd3795cfcab03bb6fc427c5ddab/waves/wallet/src/esplora.rs#L9

**Comment by thomaseizinger** [comment]
Nice to have: automated UI test using cypress.

**Comment by thomaseizinger** [comment]
We want an easy way to run a local development environment that:

- contains an esplora instance
- contains an elementd instance
- runs bobtimus, configured for the elementd instance
- instructs the wasm wallet to use the local esplora instance (see env variable above)
- starts the frontend in development mode (yarn start) so that hot-reloading works

Out of scope:

- automated testing
- serving frontend through bobtimus

**Comment by bonomat** [comment]
From https://github.com/Blockstream/esplora

> How to run the explorer for Liquid regtest
> ```
> docker run -p 50001:50001 -p 8092:80 \
>            --volume $PWD/data_liquid_regtest:/data \
>            --rm -i -t esplora \
>            bash -c "/srv/explorer/run.sh liquid-regtest explorer"
> ```
