### ISSUE TITLE
Infrastructure: Configure nigiri with a "registry" so the registry endpoint returns ticker labels & precisions

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/droplet#42]

**Comment by luckysori** [comment]
One can fetch tickers via the `ESPLORA_URL/registry` endpoint, thanks to `nigiri`'s chopsticks.

By sending a POST request to `ESPLORA_URL/registry` with the JSON body `{"assets": <array-of-asset-ids>}`, we get back the information related to all the asset IDs provided.

If instead we send `{"assets": []}` we get back information for _all_ registered assets (except for L-BTC, presumably because it was not minted via `nigiri mint`).

**Comment by thomaseizinger** [comment]
> If instead we send `{"assets": []}` we get back information for _all_ registered assets (except for L-BTC, presumably because it was not minted via `nigiri mint`).

If we manage to use a more recent docker image, this should be fixed: https://github.com/Blockstream/esplora/issues/154

**Comment by thomaseizinger** [comment]
Another issue here is that the registry doesn't return a precision.

**Comment by luckysori** [comment]
> Another issue here is that the registry doesn't return a precision.

I think esplora can return a precision: https://github.com/blockstream/esplora/blob/master/API.md#get-assetasset_id. But in the test environment we use `nigiri-chopsticks`'  registry, which does not support precision.

**Comment by thomaseizinger** [comment]
> > Another issue here is that the registry doesn't return a precision.
> 
> I think esplora can return a precision: [https://github.com/blockstream/esplora/blob/master/API.md#get-assetasset_id](https://github.com/blockstream/esplora/blob/master/API.md?rgh-link-date=2020-12-23T02%3A49%3A13Z#get-assetasset_id). But in the test environment we use `nigiri-chopsticks`' registry, which does not support precision.

How hard would it be to patch `nigiri-chopsticks` to support this?

**Comment by luckysori** [comment]
> > > Another issue here is that the registry doesn't return a precision.
> > 
> > 
> > I think esplora can return a precision: [https://github.com/blockstream/esplora/blob/master/API.md#get-assetasset_id](https://github.com/blockstream/esplora/blob/master/API.md?rgh-link-date=2020-12-23T02%3A49%3A13Z#get-assetasset_id). But in the test environment we use `nigiri-chopsticks`' registry, which does not support precision.
> 
> How hard would it be to patch `nigiri-chopsticks` to support this?

How's your Go?

**Comment by thomaseizinger** [comment]
> > > > Another issue here is that the registry doesn't return a precision.
> > > 
> > > 
> > > I think esplora can return a precision: [https://github.com/blockstream/esplora/blob/master/API.md#get-assetasset_id](https://github.com/blockstream/esplora/blob/master/API.md?rgh-link-date=2020-12-23T02%3A49%3A13Z#get-assetasset_id). But in the test environment we use `nigiri-chopsticks`' registry, which does not support precision.
> > 
> > How hard would it be to patch `nigiri-chopsticks` to support this?
> 
> How's your Go?

I haven't programmed Go since Uni, so I would say it is a bit ... rusty?

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/comit-network/droplet/issues/106 because using the registry would never guarantee the use of the "correct" assets. Even in production the asset label can easily be spoofed. Hence we definitely want to hardcode the asset ID at build-time.
